- name: Setup the web server 
  hosts: web1 
  tasks: 
    # (ㄱ) 패키지 설치  
    # - firealld 
    # - httpd,mod_ssl 
    # - mariadb-server
    # - php, php-mysqlnd, php-pdo
    - name: Install the packages 
      yum: 
        name: 
          - firewalld 
          - httpd 
          - mod_ssl 
          - mariadb-server 
          - php 
          - php-mysqlnd 
          - php-pdo 
        state: latest   
    # (ㄴ) 서비스 설정
    # - ansible web(/var/www/html/index.php) -- download -->  
    - name: Download the web page template
      get_url: 
        url: http://192.168.10.10/index.php
        dest: /var/www/html/index.php
        mode: '0644'

    # (ㄷ) 서비스 기동 
    # - firewalld, httpd
    - name: Startup the service 
      service: 
        name: "{{ item }}"
        state: started 
        enabled: yes 
      loop:
        - firewalld 
        - httpd 
    # (ㄹ) 방화벽 등록 
    # -http, https, mysql 
    - name: Open the service ports 
      firewalld: 
        service: "{{ item }}"
        permanent: true 
        state: enabled 
        immediate: yes 
      loop: 
        - http 
        - https 
        - mysql

    # - http, https mysql

- name: Test connect to web server 
  hosts: localhost
  become: no 
  tasks:
    - name: Connect to web1.example.com server  
      uri: 
        url: http://web1.example.com 
        return_content: true 
        status_code: 200
    # (ㅁ) SELinux 
