---
- name: 웹 서버 설정 
  hosts: lamp
  vars:
    firewall: firewalld
    fw_http: http
  tasks:
    # * vars/main.yml
    - name: 변수 포함 
      include_vars: vars/main.yml

    # * tasks/main.yml
    - name: 작업 포함 
      include_tasks: tasks/main.yml
    
    # 패키지 설치 - firewalld 
    - name: 패키지 설치 - {{ firewall }}
      yum:
        name: "{{ firewall }}"
        state: latest
    # 서비스 재기동 - firewalld 
    - name: Start the firewall
      service:
        name: "{{ firewall }}"
        state: restarted
        enabled: true
    # 방화벽 등록 - http 
    - name: 방화벽 등록 - {{ fw_http }}
      firewalld:
        service: "{{ fw_http }}"
        state: enabled
        immediate: true
        permanent: true
    # 웹 파일 생성 - /var/www/html/index.html 
    - name: index 파일 생성 - {{ web_root }}/index.html 
      copy:
        content: "{{ ansible_fqdn }}({{ ansible_default_ipv4.address }}) has been customized by Ansible\n"
        dest: "{{ web_root }}/index.html"
